### ISSUE TITLE
Error about tf.reshape

### ISSUE THREAD

**Issue by lkyee** [taki0112/GCNet-Tensorflow#1]
Hi，
Thanks for your nice code.But I happened to a error about tf.reshape.
 File "D:\GCNet.py", line 90, in hw_flatten
 return tf.reshape(x, shape=[x.shape[0], -1, x.shape[-1]])
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [Dimension(None), -1, Dimension(64)]. Consider casting elements to a supported type.
Can you help me solve the problem?
Look forward to your kind reply!

**Comment by taki0112** [comment]
Maybe your `batch_size` is `None`

um... can you try this code ?
```python
return tf.reshape(x, shape=[tf.shape(x)[0], -1, tf.shape(x)[-1]])
```

**Comment by lkyee** [comment]
Thank you！Your solution is working!
